config/routes.rb
Alerts::Application.routes.draw do
  resources :alarm_tasks

root :to => 'alarm_tasks#index'

end

app/models/alarm_task.rb
class AlarmTask < ActiveRecord::Base
end

app/controllers/alarm_tasks_controller.rb
class AlarmTasksController < ApplicationController
  # GET /alarm_tasks
  # GET /alarm_tasks.json
  def index
    @alarm_tasks = ''

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alarm_tasks }
    end
  end

  # GET /alarm_tasks/1
  # GET /alarm_tasks/1.json
  def show
    @alarm_task = AlarmTask.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alarm_task }
    end
  end

  # GET /alarm_tasks/new
  # GET /alarm_tasks/new.json
  def new
    @alarm_task = AlarmTask.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alarm_task }
    end
  end

  # GET /alarm_tasks/1/edit
  def edit
    @alarm_task = AlarmTask.find(params[:id])
  end

  # POST /alarm_tasks
  # POST /alarm_tasks.json
  def create
    @alarm_task = AlarmTask.new(params[:alarm_task])

    respond_to do |format|
      if @alarm_task.save
        format.html { redirect_to @alarm_task, notice: 'Alarm task was successfully created.' }
        format.json { render json: @alarm_task, status: :created, location: @alarm_task }
      else
        format.html { render action: "new" }
        format.json { render json: @alarm_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /alarm_tasks/1
  # PUT /alarm_tasks/1.json
  def update
    @alarm_task = AlarmTask.find(params[:id])

    respond_to do |format|
      if @alarm_task.update_attributes(params[:alarm_task])
        format.html { redirect_to @alarm_task, notice: 'Alarm task was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @alarm_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarm_tasks/1
  # DELETE /alarm_tasks/1.json
  def destroy
    @alarm_task = AlarmTask.find(params[:id])
    @alarm_task.destroy

    respond_to do |format|
      format.html { redirect_to alarm_tasks_url }
      format.json { head :ok }
    end
  end
end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
end

app/controllers/alert_controller.rb
class AlertController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/alarm_tasks_helper.rb
module AlarmTasksHelper
end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/helpers/alert_helper.rb
module AlertHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alarm_tasks/_form.html.erb
<%= form_for(@alarm_task) do |f| %>
  <% if @alarm_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alarm_task.errors.count, "error") %> prohibited this alarm_task from being saved:</h2>

      <ul>
      <% @alarm_task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :finished %><br />
    <%= f.check_box :finished %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alarm_tasks/edit.html.erb
<h1>Editing alarm_task</h1>

<%= render 'form' %>

<%= link_to 'Show', @alarm_task %> |
<%= link_to 'Back', alarm_tasks_path %>

app/views/alarm_tasks/index.html.erb
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />

<title>Alarms</title>
</head>
<body ng-app>
<button class='trigger' ng-click="resetAlarm()">reset Alarm(s)</button>
<h1>Listing alarm_tasks</h1>
<div ng-controller='TasksCtrl' >  
<table>
  <tr>
    <th>                                                                                                                                  
        <ul>
          <h1>Add rules triggering every Alarm</h1>
          <li ng-repeat='alarm in alarms'>
         <span class="triggered-{{alarm.triggered}}">{{alarm.title}}</span>
          </li> 
          <button class='trigger' ng-click="triggerAlarm()">Trigger Alarm(s)</button>
               
        </ul> 
    </th>
    <th>
      <ul>
        <li ng-repeat='rule in rules' >
        <input type="checkbox", class="checkedrule", value="rule.done" ng-model="rule.done" ng-init=false />
        <span>{{rule.title}}</span>
         <br/>
        </li>
        <button class='addRule' ng-click="addRule()">Add Rule</button>
      </ul>
    </th>
    <th>
      <ul>
        <li ng-repeat='alarm in alarms'>
          <input type="radio", ng-model="$parent.selected", value={{alarm.title}}/>
          <span>{{alarm.title}} </span> 
        </li>
      </ul>
      <span ng-model='radioAlarm' >{{selected}} </span>
     </th>
    </tr>
</table>
<br />
</div>

</body>

app/views/alarm_tasks/new.html.erb
<h1>New alarm_task</h1>

<%= render 'form' %>

<%= link_to 'Back', alarm_tasks_path %>

app/views/alarm_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @alarm_task.title %>
</p>

<p>
  <b>Finished:</b>
  <%= @alarm_task.finished %>
</p>


<%= link_to 'Edit', edit_alarm_task_path(@alarm_task) %> |
<%= link_to 'Back', alarm_tasks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title>Alerts</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>